.TH _PRINTF 3 "APRIL 2026" "Custom Printf Implementation"
.SH NAME
_printf \- prints formatted output to stdout
.SH SYNOPSIS
#include "main.h"
int _printf(const char *format, ...);
.SH DESCRIPTION
The _printf() function produces output according to a format.
It handles %c, %s, %%, %d, and %i.
.SH RETURN VALUE
Returns the number of characters printed.
